"use client";
import { useDraggable, useDroppable } from "@dnd-kit/core";
import { motion } from "framer-motion";
import type { FantasyCoach } from "@/data/superlig-coaches-2026";
import PlayerCard,{FantasyPlayer,PlayerPosition}from"./PlayerCard";
export type PitchSlot={id:string;index:number;position:PlayerPosition;player?:FantasyPlayer|null;invalidPosition?:boolean};export type BenchPitchSlot={id:string;position:PlayerPosition;player?:FantasyPlayer|null};
type Props={formationLabel:string;formations:readonly string[];slots:PitchSlot[];benchSlots:BenchPitchSlot[];coach?:FantasyCoach|null;captainId?:string|number|null;tripleCaptainId?:string|number|null;draggingPlayer?:FantasyPlayer|null;onFormationChange:(f:string)=>void;onPlayerClick?:(p:FantasyPlayer)=>void;onBenchPlayerClick?:(p:FantasyPlayer)=>void};
const order:PlayerPosition[]=["FWD","MID","DEF","GK"];const label:Record<PlayerPosition,string>={FWD:"FORVET",MID:"ORTA SAHA",DEF:"DEFANS",GK:"KALECİ"};const code:Record<PlayerPosition,string>={GK:"KL",DEF:"DEF",MID:"ORT",FWD:"FOR"};const base=process.env.NEXT_PUBLIC_BASE_PATH??"";const asset=(n:string)=>`${base}/game-ui/${n}`;
export default function FootballPitch(p:Props){return <section className="relative mx-auto w-full max-w-[920px] overflow-visible rounded-[30px] border border-cyan-300/15 bg-[#080d1a] p-2 shadow-[0_36px_110px_rgba(0,0,0,.70)] sm:p-2.5"><div className="relative h-[610px] overflow-hidden rounded-[24px] border border-[#dfffe9]/25 bg-[#155d29] shadow-[inset_0_0_120px_rgba(0,20,5,.60),0_24px_48px_rgba(0,0,0,.42)] sm:h-[630px] lg:h-[650px]"><img src={asset("pitch-texture.svg")} alt="" className="pointer-events-none absolute inset-0 h-full w-full object-cover"/><img src={asset("stadium-lights.svg")} alt="" className="pointer-events-none absolute inset-0 h-full w-full object-cover mix-blend-screen"/><Markings/><div className="absolute left-[4%] top-[3%] z-40"><select value={p.formationLabel} onChange={e=>p.onFormationChange(e.target.value)} className="h-10 min-w-[116px] rounded-full border border-[#f3ca40]/85 bg-[#071017]/95 px-4 text-[13px] font-black text-white">{p.formations.map(f=><option key={f}>{f}</option>)}</select></div><div className="absolute right-[4%] top-[3%] z-30 text-right"><b className="text-[12px] font-black text-[#f3ca40]">FUTBOL IQ</b></div><div className="absolute left-1/2 top-16 flex h-[calc(100%-84px)] w-[94%] -translate-x-1/2 flex-col pb-5"><div className="flex flex-1 flex-col justify-evenly">{order.map(pos=>{const a=p.slots.filter(s=>s.position===pos);return a.length?<motion.div layout="position" key={pos} className="grid h-[112px] items-center justify-items-center gap-1" style={{gridTemplateColumns:`repeat(${a.length},minmax(0,1fr))`}}>{a.map(s=><Field key={s.id} s={s} p={p}/>)}</motion.div>:null})}</div></div><div className="absolute bottom-[4.5%] right-[4%] z-30 grid h-[88px] w-[76px] place-items-center rounded-2xl border-2 border-dashed border-[#f3ca40]/85 bg-black/30 text-[9px] font-black text-[#f3ca40]">★<br/>JOKER</div></div><div className="relative mt-2 overflow-hidden rounded-[26px] border border-white/18 bg-[#07151c] p-3"><img src={asset("dugout-glass.svg")} alt="" className="pointer-events-none absolute inset-0 h-full w-full object-fill opacity-90"/><div className="relative mb-2 flex justify-between"><b className="text-[9px] tracking-[.12em]">YEDEK KULÜBESİ</b><small>{p.benchSlots.filter(s=>s.player).length}/4</small></div><div className="relative grid grid-cols-[74px_repeat(4,minmax(0,1fr))] items-end gap-1.5 sm:gap-3"><Coach coach={p.coach}/>{p.benchSlots.map(s=><Bench key={s.id}s={s}p={p}/>)}</div></div></section>}
function Field({s,p}:{s:PitchSlot;p:Props}){const ok=!p.draggingPlayer||p.draggingPlayer.position===s.position;const{setNodeRef}=useDroppable({id:s.id,disabled:!ok});return <div ref={setNodeRef} className={`relative grid h-[112px] place-items-center rounded-2xl ${s.invalidPosition?"bg-rose-500/10 ring-1 ring-rose-400/30":""}`}>{s.player?<Drag player={s.player}slot={s.id} captain={s.player.id===p.captainId} invalid={!!s.invalidPosition} click={()=>p.onPlayerClick?.(s.player!)}/>:<Empty pos={s.position}/>}</div>}
function Bench({s,p}:{s:BenchPitchSlot;p:Props}){const ok=!p.draggingPlayer||p.draggingPlayer.position===s.position;const{setNodeRef}=useDroppable({id:s.id,disabled:!ok});return <div ref={setNodeRef} className="relative grid h-[118px] place-items-center overflow-visible rounded-xl border border-white/[.07] bg-[#080d1a]/16">{s.player?<Drag player={s.player}slot={s.id} sub click={()=>p.onBenchPlayerClick?.(s.player!)}/>:<Empty pos={s.position}/>}</div>}
function Drag({player,slot,captain=false,sub=false,invalid=false,click}:{player:FantasyPlayer;slot:string;captain?:boolean;sub?:boolean;invalid?:boolean;click?:()=>void}){const d=useDraggable({id:`player:${player.id}`,data:{sourceSlotId:slot}});const style=d.transform?{transform:`translate3d(${d.transform.x}px,${d.transform.y}px,0)`,touchAction:"none" as const}:{touchAction:"none" as const};return <div ref={d.setNodeRef} style={style}{...d.listeners}{...d.attributes} className={d.isDragging?"relative z-20 opacity-25":"relative z-20"}><PlayerCard compact player={player} captain={captain} substitute={sub} invalidPosition={invalid} onClick={click}/></div>}
function Empty({pos}:{pos:PlayerPosition}){return <div className="grid h-[100px] w-full max-w-[82px] place-items-center rounded-2xl border border-dashed border-white/16 bg-black/10"><span className="rounded-md border border-[#ffe88a]/30 bg-[#07111d]/95 px-2 py-1 text-[9px] font-black tracking-[.05em] text-[#fff0a2]">{code[pos]}</span></div>}
function Coach({coach}:{coach?:FantasyCoach|null}){return <div className="relative mx-auto h-[92px] w-[66px] overflow-hidden rounded-[15px] border border-violet-300/50 bg-[#17142f]"><span className="absolute left-1 top-1 text-[7px] font-black text-cyan-200">TD</span><div className="absolute left-1/2 top-4 h-12 w-10 -translate-x-1/2 rounded-t-full bg-[#20334f]"/><b className="absolute inset-x-1 bottom-1 truncate bg-[#080d1a]/90 p-1 text-center text-[6px]">{coach?.name??"TEKNİK DİREKTÖR"}</b></div>}
function Markings(){return <><div className="absolute inset-[2.8%] border-2 border-white/65"/><div className="absolute left-[2.8%] right-[2.8%] top-1/2 border-t-2 border-white/60"/><div className="absolute left-1/2 top-1/2 h-[120px] w-[120px] -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white/60"/><div className="absolute left-1/2 top-[2.8%] h-[82px] w-[220px] -translate-x-1/2 border-x-2 border-b-2 border-white/55"/><div className="absolute bottom-[2.8%] left-1/2 h-[82px] w-[220px] -translate-x-1/2 border-x-2 border-t-2 border-white/55"/></>}
