import Link from "next/link";
import type { CSSProperties } from "react";
import { FANTASY_PLAYER_POOL } from "@/data/fantasy-player-pool";
const base=process.env.NEXT_PUBLIC_BASE_PATH??"";
const positions=[["GK","Kaleci"],["DEF","Defans"],["MID","Orta Saha"],["FWD","Forvet"]] as const;
const weeklyBest=positions.map(([position,label])=>({position,label,player:[...FANTASY_PLAYER_POOL].filter(p=>p.position===position).sort((a,b)=>b.points-a.points||b.price-a.price)[0]}));
function Symbol({kind}:{kind:"calendar"|"cup"|"iq"|"star"|"weekly"}){const paths={calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 11h18M7 15h3m4 0h3"/></>,cup:<><path d="M8 3h8v7a4 4 0 0 1-8 0V3ZM8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4M12 14v6m-5 1h10"/></>,iq:<><path d="M8 17c0-4-3-5-3-8a7 7 0 0 1 14 0c0 3-3 4-3 8ZM9 21h6m-3-9V7"/></>,star:<path d="m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1Z"/>,weekly:<><path d="M8 3h8v5a4 4 0 0 1-8 0V3Z"/><path d="M6 4H3v2a4 4 0 0 0 5 4M18 4h3v2a4 4 0 0 1-5 4M12 12v4M8 20h8"/><path d="m12 15 1.2 2.3 2.6.4-1.9 1.8.5 2.5-2.4-1.2L9.6 22l.5-2.5-1.9-1.8 2.6-.4L12 15Z"/></>};return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6">{paths[kind]}</svg>}
function PanelTitle({kind,title,href,action}:{kind:"calendar"|"cup"|"star"|"weekly";title:string;href:string;action:string}){return <div className="home-panel-title"><h2><Symbol kind={kind}/>{title}</h2><Link href={href}>{action} <span aria-hidden="true">→</span></Link></div>}
function RuleIcon({kind}:{kind:"budget"|"players"|"club"|"captain"}){
 const shapes={budget:<><path d="M19 7H5a2 2 0 0 1 0-4h12v4M4 7v13h16V7"/><path d="M20 11h-6v5h6"/><circle cx="16.5" cy="13.5" r=".6"/></>,players:<><circle cx="12" cy="7" r="3"/><path d="M6 21v-4a6 6 0 0 1 12 0v4M3 6a3 3 0 0 1 0 6m18-6a3 3 0 0 0 0 6M2 21v-5m20 5v-5"/></>,club:<><path d="m12 2 8 3v7c0 5-8 10-8 10S4 17 4 12V5Z"/><path d="M9 8h4a2 2 0 0 1 0 4h-2m2 0a2 2 0 0 1 0 4H9"/></>,captain:<><rect x="3" y="5" width="18" height="14" rx="4"/><path d="M7 5v14M17 5v14m-3-9a3 3 0 1 0 0 4"/></>};
 return <svg className="home-rule-icon" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{shapes[kind]}</svg>;
}
function Shield({style}:{style?:CSSProperties}){return <div className="home-shield" style={style}><svg viewBox="0 0 50 60" aria-hidden="true"><circle cx="25" cy="19" r="8"/><path d="M9 50v-9c0-14 32-14 32 0v9Z"/></svg></div>}
function Stadium(){const spots=[[32,17],[50,12],[68,17],[27,39],[50,36],[73,39],[17,62],[39,60],[61,60],[83,62],[50,82]];return <div className="home-stadium" role="img" aria-label="4-3-3 dizilişinde 11 futbolcu ve 4 yedekten oluşan temsili kadro"><span className="home-stadium-motto">İYİ HAMLELER<br/>BÜYÜK HİKÂYELER YAZAR</span><div className="home-pitch"><svg className="home-pitch-lines" viewBox="0 0 600 400" preserveAspectRatio="none" aria-hidden="true"><g fill="none" stroke="#d7f3c0" strokeWidth="2" opacity=".65"><path d="M116 12h368l103 373H13ZM64 201h472M239 12l-8 45h138l-8-45M192 385l12-77h192l12 77M260 12l-3 20h86l-3-20M242 385l4-34h108l4 34"/><ellipse cx="300" cy="201" rx="54" ry="31"/></g></svg>{spots.map(([x,y],i)=><Shield key={i} style={{left:`${x}%`,top:`${y}%`}}/>)}</div><div className="home-bench" style={{backgroundImage:`url(${base}/game-ui/dugout-realistic.webp)`}}>{Array.from({length:4},(_,i)=><Shield key={i}/>)}</div></div>}
export default function Home(){return <div className="fiq-home" style={{"--home-stadium":`url(${base}/game-ui/stadium-bowl.webp)`,"--home-athletes":`url(${base}/game-ui/home-athletes.webp)`} as CSSProperties}>
 <section className="home-hero"><div className="home-hero-copy"><p className="home-eyebrow">SÜPER LİG FANTEZİ FUTBOL</p><h1>Futbolu oku.<br/>Kadronla fark yarat.</h1><p className="home-intro">Bilgini sahaya yansıt. Kendi takımını kur,<br className="home-desktop-break"/> haftanın heyecanına ortak ol.</p><div className="home-analysis-slot"><a className="home-analysis-entry home-analysis-art" href={`${base}/tff-scout.html`} aria-label="FUTBOL IQ analiz sayfasını aç"><img className="home-analysis-image" src={`${base}/game-ui/analysis-original-20260920.jpg`} width="1376" height="768" alt="Football IQ analiz platformu: saha, oyuncu hareketleri ve istatistik panelleri" loading="eager" fetchPriority="high" decoding="async"/></a></div><div className="home-actions"><Link href="/team"><span className="home-action-emoji" aria-hidden="true">👥</span><span>KADRONU KUR</span><b aria-hidden="true">→</b></Link><Link href="/rules"><span className="home-action-emoji" aria-hidden="true">📜</span><span>OYUN KURALLARI</span></Link></div><div className="home-rule-chips home-rule-chips-simple" aria-label="Kadro kuralları"><div><RuleIcon kind="budget"/><p>100M<b>Bütçe</b></p></div><div><RuleIcon kind="players"/><p>11 + 4<b>Oyuncu</b></p></div><div><RuleIcon kind="club"/><p>En fazla 3<b>Aynı kulüpten</b></p></div><div><RuleIcon kind="captain"/><p>×2<b>Kaptan puanı</b></p></div></div></div><Stadium/></section>
 <section className="home-panel home-players"><PanelTitle kind="weekly" title="Haftanın Oyuncuları" href="/team" action="🏟️ Kadroyu Aç"/><div className="home-position-cards">{weeklyBest.map(({label,player},i)=><Link href="/team" key={label} className={`home-position-card home-position-${i}`}><div className="home-weekly-rank"><span>{label}</span><b>#{i+1}</b></div><div className="home-weekly-copy"><h3>{player?.name??"Veri bekleniyor"}</h3><i/><p>{player?player.club:"Oyuncu verisi bekleniyor."}</p>{player?<strong>{player.points} P</strong>:null}</div><span className="home-position-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
 <section className="home-next" aria-label="Hızlı başlangıç"><div><span className="home-eyebrow">SIRADAKİ HAMLE SENİN</span><h2>Maça hazırlan.</h2><p>Kadronu kur, oyuncuları incele ve FUTBOL IQ analizlerini kullan.</p></div><Link href="/team"><b aria-hidden="true">⚽</b><span>Kadrom<strong>Takımını sahaya çıkar</strong></span><i aria-hidden="true">↗</i></Link></section>
 
 <div className="home-signoff"><span>FUTBOL IQ <b>DAHA FAZLA DÜŞÜN. DAHA İYİ OYNA.</b></span><span>2026–27 · GELİŞTİRME ÖNİZLEMESİ</span></div>
 </div>}
