import Link from "next/link";
import type { CSSProperties } from "react";
const base=process.env.NEXT_PUBLIC_BASE_PATH??"";
const fixtures=[["Galatasaray","Beşiktaş"],["Fenerbahçe","Trabzonspor"],["Samsunspor","Başakşehir"]];
const clubs=["Beşiktaş","Fenerbahçe","Galatasaray","Trabzonspor"];
const positions=["Kaleci","Defans","Orta Saha","Forvet"];
function Mark({name}:{name:string}){return <span className="home-club-mark" aria-hidden="true">{name[0]}</span>}
function Symbol({kind}:{kind:"calendar"|"cup"|"iq"|"star"}){const paths={calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 11h18M7 15h3m4 0h3"/></>,cup:<><path d="M8 3h8v7a4 4 0 0 1-8 0V3ZM8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4M12 14v6m-5 1h10"/></>,iq:<><path d="M8 17c0-4-3-5-3-8a7 7 0 0 1 14 0c0 3-3 4-3 8ZM9 21h6m-3-9V7"/></>,star:<path d="m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1Z"/>};return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6">{paths[kind]}</svg>}
function PanelTitle({kind,title,href,action}:{kind:"calendar"|"cup"|"star";title:string;href:string;action:string}){return <div className="home-panel-title"><h2><Symbol kind={kind}/>{title}</h2><Link href={href}>{action} <span aria-hidden="true">→</span></Link></div>}
function Shield({style}:{style?:CSSProperties}){return <div className="home-shield" style={style}><svg viewBox="0 0 50 60" aria-hidden="true"><circle cx="25" cy="19" r="8"/><path d="M9 50v-9c0-14 32-14 32 0v9Z"/></svg></div>}
function Stadium(){const spots=[[32,17],[50,12],[68,17],[27,39],[50,36],[73,39],[17,62],[39,60],[61,60],[83,62],[50,82]];return <div className="home-stadium" role="img" aria-label="4-3-3 dizilişinde 11 futbolcu ve 4 yedekten oluşan temsili kadro"><span className="home-stadium-motto">İYİ HAMLELER<br/>BÜYÜK HİKÂYELER YAZAR</span><div className="home-pitch"><svg className="home-pitch-lines" viewBox="0 0 600 400" preserveAspectRatio="none" aria-hidden="true"><g fill="none" stroke="#d7f3c0" strokeWidth="2" opacity=".65"><path d="M116 12h368l103 373H13ZM64 201h472M239 12l-8 45h138l-8-45M192 385l12-77h192l12 77M260 12l-3 20h86l-3-20M242 385l4-34h108l4 34"/><ellipse cx="300" cy="201" rx="54" ry="31"/></g></svg>{spots.map(([x,y],i)=><Shield key={i} style={{left:`${x}%`,top:`${y}%`}}/>)}</div><div className="home-bench" style={{backgroundImage:`url(${base}/game-ui/dugout-realistic.webp)`}}>{Array.from({length:4},(_,i)=><Shield key={i}/>)}</div></div>}
export default function Home(){return <div className="fiq-home" style={{"--home-stadium":`url(${base}/game-ui/stadium-bowl.webp)`,"--home-athletes":`url(${base}/game-ui/home-athletes.webp)`} as CSSProperties}>
 <section className="home-hero"><div className="home-hero-copy"><p className="home-eyebrow">SÜPER LİG FANTEZİ FUTBOL</p><h1>Futbolu oku.<br/>Kadronla fark yarat.</h1><p className="home-intro">Bilgini sahaya yansıt. Kendi takımını kur,<br className="home-desktop-break"/> haftanın heyecanına ortak ol.</p><div className="home-actions"><Link href="/team">KADRONU KUR <span aria-hidden="true">→</span></Link><Link href="/rules">OYUN KURALLARI</Link></div><div className="home-rule-chips" aria-label="Kadro kuralları">{[["◈","100M","Bütçe"],["♟","11 + 4","Oyuncu"],["◇","Kulüp Başına","3"],["★","Kaptan","×2"]].map(([icon,title,value])=><div key={title}><span aria-hidden="true">{icon}</span><p>{title}<b>{value}</b></p></div>)}</div></div><Stadium/></section>
 <section className="home-panel home-players"><PanelTitle kind="star" title="Oyuncu Rehberi" href="/team" action="Oyuncuları İncele"/><div className="home-position-cards">{positions.map((position,i)=><Link href="/team" key={position} className={`home-position-card home-position-${i}`}><svg viewBox="0 0 130 130" aria-hidden="true"><circle cx="70" cy="28" r="12"/><path d={i===0?"M55 46 28 58 7 39l-7 8 28 28 21-9-9 29-27 25 12 9 34-27 17-24 25 15 15-5-30-28-4-17Z":"M55 44 27 68l7 9 24-14-6 29-20 29 13 8 26-32 11 8 8 24 16-3-9-33-17-17 4-18 15 17 22-7-4-10-14 2-17-18Z"}/></svg><div><h3>{position}</h3><i/><p>Veri bekleniyor.</p></div><span className="home-position-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
 <section className="home-next" aria-label="Hızlı başlangıç"><div><span className="home-eyebrow">SIRADAKİ HAMLE SENİN</span><h2>Maça hazırlan.</h2><p>Kadronu kur, rakipleri incele, ligi takip et.</p></div><Link href="/team"><b>01</b><span>Kadrom<strong>Takımını sahaya çıkar</strong></span><i aria-hidden="true">↗</i></Link><Link href="/today"><b>02</b><span>Fikstür<strong>Eşleşmeleri incele</strong></span><i aria-hidden="true">↗</i></Link><Link href="/leagues/super-lig"><b>03</b><span>Puan Durumu<strong>Lig tablosunu keşfet</strong></span><i aria-hidden="true">↗</i></Link></section><div className="home-dashboard"><section className="home-panel"><PanelTitle kind="calendar" title="Haftanın Fikstürü" href="/today" action="Tüm Fikstür"/><div className="home-fixtures">{fixtures.map(([a,b])=><div className="home-match" key={a}><span><Mark name={a}/>{a}</span><small>Örnek eşleşme<b>—</b></small><span><Mark name={b}/>{b}</span></div>)}</div></section>
 <section className="home-panel"><PanelTitle kind="cup" title="Puan Durumu" href="/leagues/super-lig" action="Tüm Tablo"/><table className="home-standings"><caption className="sr-only">Süper Lig takımları; resmî sıralama verisi bekleniyor</caption><thead><tr><th scope="col">TAKIM</th><th scope="col">O</th><th scope="col">P</th></tr></thead><tbody>{clubs.map(club=><tr key={club}><th scope="row">{club}</th><td>—</td><td>—</td></tr>)}</tbody></table><p className="home-data-note">Alfabetik görünüm · Sezon verileri bekleniyor.</p></section>
 <section className="home-panel home-iq"><a className="home-iq-entry" href={`${base}/tff-scout.html`} aria-label="FUTBOL IQ verilerle oku ve tek tuşla en iyi 15 kadro kurucuyu aç"><div className="home-panel-title"><h2><Symbol kind="iq"/>Football IQ <span className="home-live">AKTİF</span></h2></div><svg className="home-tactics" viewBox="0 0 130 140" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1.3"><path d="M10 10h110v120H10ZM10 70h110M45 10v24h40V10M45 130v-24h40v24M35 100l43-37m-14 2 14-2-3 14"/><circle cx="65" cy="70" r="20"/><circle cx="30" cy="40" r="4"/><circle cx="97" cy="95" r="4"/><path d="m94 36 8 8m0-8-8 8m-65 28 8 8m0-8-8 8"/></g></svg><h3>Oyunu verilerle oku</h3><p>Daha iyi kararlar için<br/>istatistiklerin gücünü kullan.</p><ul><li><span aria-hidden="true">▥</span>Oyuncu<br/>analizi</li><li><span aria-hidden="true">↗</span>Form ve<br/>fikstür</li><li><span aria-hidden="true">♟</span>Kadro<br/>önerileri</li></ul><span className="home-iq-cta">VERİLERLE OKU <b aria-hidden="true">→</b></span></a></section></div>
 
 <div className="home-signoff"><span>FUTBOL IQ <b>DAHA FAZLA DÜŞÜN. DAHA İYİ OYNA.</b></span><span>2026–27 · GELİŞTİRME ÖNİZLEMESİ</span></div>
 </div>}
