"use client";

import { lockInert } from "@/lib/inert-lock";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect,useRef,useState } from "react";
import type { ReactNode } from "react";
import { useTeamStore,type JokerKey } from "@/store/useTeamStore";

function Icon({name}:{name:string}){const common={width:20,height:20,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};const paths:Record<string,ReactNode>={home:<><path d="M3 11.5 12 4l9 7.5"/><path d="M5 10v10h14V10"/></>,leagues:<><path d="M8 4h8v4a4 4 0 0 1-8 0V4Z"/><path d="M6 5H4v2a4 4 0 0 0 4 4M18 5h2v2a4 4 0 0 1-4 4M12 12v5M8 20h8"/></>,team:<><circle cx="12" cy="7" r="3"/><path d="M5 21c.5-5 2.8-7 7-7s6.5 2 7 7"/></>,transfer:<><path d="M7 7h12l-3-3M17 17H5l3 3"/></>,live:<><circle cx="12" cy="12" r="2"/><path d="M7.8 7.8a6 6 0 0 0 0 8.4M16.2 7.8a6 6 0 0 1 0 8.4M4.6 4.6a10.5 10.5 0 0 0 0 14.8M19.4 4.6a10.5 10.5 0 0 1 0 14.8"/></>,joker:<><path d="m12 3 2.1 5.2 5.6.4-4.3 3.6 1.4 5.4-4.8-3-4.8 3 1.4-5.4-4.3-3.6 5.6-.4L12 3Z"/></>,profile:<><circle cx="12" cy="8" r="4"/><path d="M4 21c.7-5 3.2-7 8-7s7.3 2 8 7"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 7h18s-3 0-3-7M10 19a2 2 0 0 0 4 0"/></>,menu:<path d="M4 7h16M4 12h16M4 17h16"/>,share:<><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.7 6.8-4.1M8.6 13.3l6.8 4.1"/></>};return <svg {...common} aria-hidden="true">{paths[name]??paths.home}</svg>}
function Crown(){return <svg className="brand-crown" viewBox="0 0 32 24" aria-hidden="true"><path d="M3 20 1 6l8 6 7-10 7 10 8-6-2 14H3Z"/><path d="M4 23h24"/></svg>}

import { shareOrCopy } from "@/lib/share";

const navigation=[["Ana Sayfa","/"],["Kadrom","/team"]] as const;

export function ScoutVisualButton(){
 const base=process.env.NEXT_PUBLIC_BASE_PATH||"/football-iq";
 const image=`${base}/game-ui/futbol-iq-analysis-approved.webp`;
 return <a href={`${base}/tff-scout.html`} className="fiq-scout-visual" aria-label="FUTBOL IQ analiz sayfasını aç">
  <img className="fiq-scout-banner-image" src={image} alt="FUTBOL IQ analiz sayfasına giriş"/>
 </a>
}
export function Header(){
 const base=process.env.NEXT_PUBLIC_BASE_PATH??"";const path=usePathname();const pathname=(base&&path.startsWith(base)?path.slice(base.length):path).replace(/\/$/,"")||"/";const isTeam=pathname==="/team";
 const[open,setOpen]=useState(false);const[jokerOpen,setJokerOpen]=useState(false);
 const[notice,setNotice]=useState("");const[manual,setManual]=useState({title:"",text:""});
 const menu=useRef<HTMLElement>(null);const trigger=useRef<HTMLButtonElement>(null);const shareDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const show=(event:Event)=>{const detail=(event as CustomEvent<{title:string;text:string}>).detail;if(detail&&typeof detail.text==="string"){setManual(detail);shareDialog.current?.showModal()}};window.addEventListener("fiq-manual-share",show);return()=>window.removeEventListener("fiq-manual-share",show)},[]);
 useEffect(()=>{if(!open)return;const release=lockInert(Array.from(document.querySelectorAll<HTMLElement>("main,.fiq-header")));menu.current?.querySelector<HTMLButtonElement>("button")?.focus();function key(event:KeyboardEvent){if(event.key==="Escape"){event.preventDefault();setOpen(false)}if(event.key!=="Tab")return;const nodes=Array.from(menu.current?.querySelectorAll<HTMLElement>("button,a[href]")??[]).filter(el=>el.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}document.addEventListener("keydown",key);return()=>{release();document.removeEventListener("keydown",key);trigger.current?.focus({preventScroll:true})}},[open]);
 useEffect(()=>{setOpen(false)},[pathname]);
 useEffect(()=>{const media=window.matchMedia("(min-width:601px) and (min-height:601px)");const update=()=>{if(media.matches)setOpen(false)};media.addEventListener("change",update);return()=>media.removeEventListener("change",update)},[]);
 async function recommend(){const result=await shareOrCopy({title:"FUTBOL IQ",text:"FUTBOL IQ’da kendi fantezi futbol takımını kur!",url:window.location.origin+(process.env.NEXT_PUBLIC_BASE_PATH??"")+"/"});if(result==="copied")setNotice("Site bağlantısı kopyalandı.")}
 function share(){if(isTeam){const event=new Event("fiq-share-squad",{cancelable:true});window.dispatchEvent(event);if(event.defaultPrevented)return}void recommend()}
 return <><header className="fiq-header"><a href={`${base}/`} className="fiq-logo"><Crown/><span>FUTBOL <b>IQ</b></span></a><nav className="fiq-desktop-nav" aria-label="Ana menü">{isTeam?<><a href={`${base}/`}>Ana Sayfa</a><a href={`${base}/team/`} className="active" aria-current="page">Kadrom</a><a href={`${process.env.NEXT_PUBLIC_BASE_PATH??""}/tff-scout.html`}>Analiz</a></>:navigation.map(([label,href])=><Link key={href} aria-current={pathname===href?"page":undefined} className={pathname===href?"active":""} href={href}>{label}</Link>)}</nav><div className="fiq-header-actions">
 <button type="button" className="fiq-header-share" aria-label={isTeam?"Kadromu paylaş":"Arkadaşıma öner"} onClick={share}><Icon name="share"/><span>{isTeam?"Paylaş":"Arkadaşıma öner"}</span></button>
 <button type="button" ref={trigger} className="menu-trigger fiq-menu-toggle" aria-label="Menüyü aç" aria-expanded={open} aria-controls="fiq-mobile-menu" onClick={()=>setOpen(true)}><Icon name="menu"/><span>MENÜ</span></button>
 </div></header>
 {notice?<div className="fiq-share-notice" role="status"><span>{notice}</span><button onClick={()=>setNotice("")} aria-label="Bildirimi kapat">×</button></div>:null}
 {open?<div className="mobile-drawer-backdrop" onClick={()=>setOpen(false)}><aside ref={menu} id="fiq-mobile-menu" role="dialog" aria-modal="true" aria-label="Gezinme menüsü" className="mobile-drawer" onClick={e=>e.stopPropagation()}><div className="fiq-menu-heading"><strong>FUTBOL IQ</strong><button aria-label="Menüyü kapat" onClick={()=>setOpen(false)}>×</button></div>{isTeam?<><a href={`${base}/`}>Ana Sayfa</a><a href={`${base}/team/`}>Kadrom</a><a href={`${process.env.NEXT_PUBLIC_BASE_PATH??""}/tff-scout.html`}>Analiz</a></>:navigation.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}{isTeam?<button onClick={()=>{setOpen(false);window.dispatchEvent(new Event("fiq-open-transfers"))}}>Transfer Merkezi</button>:null}<Link href="/rules" onClick={()=>setOpen(false)}>Nasıl oynanır?</Link><button onClick={()=>{setOpen(false);setJokerOpen(true)}}>Jokerler</button></aside></div>:null}
 <dialog ref={shareDialog} className="fiq-manual-share" onClick={e=>{if(e.target===e.currentTarget){const b=e.currentTarget.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)e.currentTarget.close()}}} aria-label="Paylaşım metni"><h2>{manual.title}</h2><p>Paylaşım açılmazsa aşağıdaki metni seçip kopyalayabilirsin.</p><textarea readOnly value={manual.text} aria-label="Kopyalanacak paylaşım metni" onFocus={e=>e.currentTarget.select()}/><div className="fiq-share-dialog-actions"><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(manual.text);setNotice("Paylaşım metni kopyalandı.");shareDialog.current?.close()}catch{setNotice("Metni seçip kopyalayabilirsin.")}}}>Metni kopyala</button><button type="button" onClick={async()=>{if(!navigator.share){setNotice("Bu tarayıcıda metni kopyalayarak paylaşabilirsin.");return}try{await navigator.share({title:manual.title,text:manual.text})}catch(error){if(!(error instanceof DOMException&&error.name==="AbortError"))setNotice("Paylaşım açılamadı; metni kopyalayabilirsin.")}}}>Paylaş…</button><button onClick={()=>shareDialog.current?.close()}>Kapat</button></div></dialog>
 {jokerOpen?<JokerModal onClose={()=>setJokerOpen(false)}/>:null}</>;
}
function JokerModal({onClose}:{onClose:()=>void}){const{jokers,activateJoker}=useTeamStore();const[pending,setPending]=useState<JokerKey|null>(null);const items:[JokerKey,string,string][]=[["tripleCaptain","3x Kaptan","Kaptanın haftalık puanını 3 ile çarpar."],["benchBoost","Yedek Güç","4 yedeğin puanını haftalık skora ekler."],["wildcard","Wildcard","Transfer kısıtlarını bu hafta kaldırır."],["goldenBench","Altın Yedek","FUTBOL IQ özel joker altyapısı."]];function confirm(){if(!pending)return;activateJoker(pending);setPending(null);if("vibrate" in navigator)navigator.vibrate?.(10)}return <div className="fixed inset-0 z-[200] grid place-items-end bg-black/70 p-3 backdrop-blur-sm sm:place-items-center" onClick={onClose}><section role="dialog" aria-modal="true" className="fiq-readable-dialog w-full max-w-[520px] rounded-[26px] border border-[#f3ca40]/20 bg-[linear-gradient(180deg,#0b1d2b,#061019)] p-4 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mb-3 flex items-center justify-between"><div><span className="text-[8px] font-black tracking-[.16em] text-[#f3ca40]">FUTBOL IQ</span><h2 className="text-xl font-black text-white">Joker Merkezi</h2></div><button onClick={onClose} className="h-9 w-9 rounded-full border border-white/10 text-white/60">×</button></div><div className="grid gap-2">{items.map(([key,title,desc])=><button key={key} disabled={jokers[key]} onClick={()=>setPending(key)} className={`rounded-xl border p-3 text-left ${jokers[key]?"border-white/5 bg-white/[.02] opacity-40":"border-white/10 bg-white/[.035] hover:border-[#f3ca40]/35"}`}><strong className="block text-[11px] text-white">{title}</strong><small className="text-[8px] text-white/45">{jokers[key]?"KULLANILDI":desc}</small></button>)}</div>{pending?<div className="mt-3 rounded-xl border border-amber-300/20 bg-amber-300/[.05] p-3"><p className="text-[9px] text-amber-100/75">Bu joker sezonda/kurala göre sınırlı kullanılabilir. Etkinleştirmek istiyor musun?</p><div className="mt-2 flex gap-2"><button onClick={()=>setPending(null)} className="flex-1 rounded-lg border border-white/10 py-2 text-[9px] text-white/60">Vazgeç</button><button onClick={confirm} className="flex-1 rounded-lg border border-[#f3ca40]/40 bg-[#f3ca40]/15 py-2 text-[9px] font-black text-[#ffe57c]">Onayla</button></div></div>:null}</section></div>}
export function Footer(){return <footer className="fiq-footer"><div><span className="footer-logo">FUTBOL <b>IQ</b> Fantasy</span><small>Strateji. Bilgi. Tutku.</small></div><p>Gerçek veri bağlantısı olmayan bölümler demo olarak işaretlenir. Tahminler kesin sonuç değildir.</p></footer>}
